export enum ActionTypes {
  TOGGLE_MENU,
  DISABLE_MENU,
  HOVER_MENU,
  TOGGLE_CONTEXT_MENU,
  SET_CLICKED_POINTS,
  SET_WINDOW_SIZE,
  TOGGLE_NEWMAP_WINDOW,
  CREATE_MAP,
  ADD_HOSTSTATION,
  ADD_SQUAD,
  SELECT_UNIT,
}
